---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1c6mdht8t32akamkzrlll7ntvcueezvx976kerzga96hy4agkqcgqe3y9kq
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1c6mdht8t32akamkzrlll7ntvcueezvx976kerzga96hy4agkqcgqe3y9kq
