---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1nflvr7edzmucrcqs0spzzf8yk575c8lh9kkk7hvpgf8un5hmaqksve3xuq
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1nflvr7edzmucrcqs0spzzf8yk575c8lh9kkk7hvpgf8un5hmaqksve3xuq
