---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1xpz0vkfkhz8uwtuzwad9sqd50lkkc6k04qww5stnsxr62p5jmszsaxyzdc
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1xpz0vkfkhz8uwtuzwad9sqd50lkkc6k04qww5stnsxr62p5jmszsaxyzdc
