---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1cppk2mmfs9aq58wveyktr4xjcg3vfju506qn282z3z0ml0eejd4qtvcda4
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1cppk2mmfs9aq58wveyktr4xjcg3vfju506qn282z3z0ml0eejd4qtvcda4
