---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age18dxgvjn0kuzye00xyzrp0yt59syxj3fvl82arunej35lgr2wg9gsmk6cnd
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age18dxgvjn0kuzye00xyzrp0yt59syxj3fvl82arunej35lgr2wg9gsmk6cnd
