---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age17ue8uar6z3w02dtv8knq5d6889xwq4wdrnnt7kdwa90v0kfmhetqawzzr3
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age17ue8uar6z3w02dtv8knq5d6889xwq4wdrnnt7kdwa90v0kfmhetqawzzr3
