---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1gptpefawdagy0w89amqv83uearhdn7je2vs8gf9yydd02hkfupnsckgnkc
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1gptpefawdagy0w89amqv83uearhdn7je2vs8gf9yydd02hkfupnsckgnkc
