kind: Secret
ansible_user: ENC[AES256_GCM,data:oZk7eBu/jg==,iv:3DS0lRpIJx1Z6MMOKha1ESRxw/GekMj9jVh53ktEz7g=,tag:CwpidB6bTeGxkwfHsax/mw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:SDehEshO8+E=,iv:fZYR/AuDicPQlgfhcfoObOJGayeD+GR/HxVnTGQ3GUs=,tag:d0wESajt5Dily9Y7WIbZvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15mqr05vqgqh5h5rfa27ym6r8jgpdtpxy8j8wlnx5a42ptdan53kq6c0u4j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RkorNk5qTEs1ekZvVkt5
            TnBzK2dOV3JXYUM3anpxTnFINnZmbXVJSGpvCkZDV0Y0K2lqcnNNWDc2SVY2NFpp
            UkpmZVZ5dTFtTjAvSHl6VWNMNlZmWGcKLS0tIG1FOWdWYyswc2YxTGlVekdqUXAz
            aWdScjNnWXlqOFF4bXcvZnpYdXhVVkEKAl+w6wq+3V/2bK2SxwyczBxd+OMLDLR0
            5xA08nT/Fm1nlVN5OwdHjyd/hjMKWS5tq197OHBOcq5j/Mz+lKEoKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-06T08:51:57Z"
    mac: ENC[AES256_GCM,data:ZMxmbXUk3wsPyU2npUfr2xn3A4tdCoPoquA0DoQZrf13tmnngE+XYRbANp87t+rW7UKdIJS4D3S30LEzBpQvMy61ITshPx33JuZ1v6WcKDvkWW0k2Dd4Z7CGDTwfoygGkB8FCYFxOZop3hBFYK23UEOFb9BCKLd2G8mS3+F5LdI=,iv:YLpyd1pKZhWI4PYgKqJ0xeOHlASg7l8A1gS9ROrPIck=,tag:BbRtgrBp3uo+LEAIouhWfA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
