kind: Secret
ansible_user: ENC[AES256_GCM,data:t+pD/amU6A==,iv:qVsXd+mitxNXZ0iQhTyF+WEv/z1UNNmZhvUKb34yRUI=,tag:UoXo/66AeK1O3ClwYXuu+A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ASMyk7f9P+M=,iv:0vr/aArqXbr+QItBub5Q3HaFxpIiFFI3+i8JSuKlH0s=,tag:B5HQoRGFdu67h4wEVubXpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekhztvazxdqa67xyu2v0fy9cn6y8t6awta2wnrz66agv2dmq7g0qfkg7lp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRDRDSnZENHBvL2UwT1A1
            MEZoSFpRdlplRm16SFpqdWFnNnBRVFNPMnhNCnQ1c29idEJoWkRaQXNPR1lPQkxV
            aStLbnFucnVmdnoya0lqZTdybXVVWTgKLS0tIEs2MmllK3NIR3A5akt1aHZNMGVB
            ZzFzRjZyUVhnczRmbE1ZSWF2REwrREEK7DdSsoqcXv2OCjCmPWJRiVIYnDGjp232
            L+vVJGtAHC/WazLIPvd1lNf3v0uchDvP7uztxNmyQ5+gB2f6EMkeOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T11:38:02Z"
    mac: ENC[AES256_GCM,data:wyxIMCIOraGt0at5OXiZ+O+jQGrw2aKakDAJ5E3c7fb6ExqTmdCZ8FUDl6bxKxTH7nWij9MsYBb2Tev4tvtNciO0j7hCy2JY5Y1qjjy2DxdtTbR0YyIAivxCzIu3nZyg9DVEVTqli9qXVU7uiP+n+PiTgkuvSN+r5rwfZLMz8kA=,iv:BiRm1UXTi508GzRjCE1i/0K9nCEmdnxOrh6Eizx3RQI=,tag:Xv1sfwhiodxRwnnCXwGo3Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
