apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-settings
    namespace: flux-system
data:
    METALLB_LB_RANGE: ENC[AES256_GCM,data:CUfVqT7+SWHNlQPax5qz441dg7Y1ClOBcOhS2v4=,iv:VvIvxyyo7iOiZVJE+Hw3JJGD77dljiQHqngfJCnS5/Q=,tag:SE+1LzabHv6DaxInCoi3sw==,type:str]
    METALLB_TRAEFIK_ADDR: ENC[AES256_GCM,data:OI8PLuobvAOOL1DnLbI=,iv:Uj+IT1XEsSB1ubkOL0JOzUnG4yEYtKGROfLFchIepMQ=,tag:FvPO0CUE8ZoEsXPsUmhjiw==,type:str]
    #ENC[AES256_GCM,data:JnJvzj47nBETVbQO3Bny/6Lz,iv:PM0aoEf0JoMPaUI/qsFhkiG3RUHvbkyOdZjJ8Tseaiw=,tag:HBCTX16z7+Jt/ep5S5BAsA==,type:comment]
    LB_PLEX: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ue8uar6z3w02dtv8knq5d6889xwq4wdrnnt7kdwa90v0kfmhetqawzzr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdXJvSnQxVUQwZHhiSmty
            aWhxbDd3eDlZSXgxUGZIMjBxZloyWlJFYVNvCmVsWG1oRGtzeDlPM0lmZGxOQWtP
            cTJ5ZktoYk1QYmRYRVRFMzBqOEp0ZHMKLS0tIGJhSnZoa1kveVAvWHlXeHc5OElO
            Tjg4YXN3cmN0TVZIbjMyem9JaUg0TncKe1N9h5FuR5drY578fCGmqT2NlXWeTiFC
            OaS95RfvWgeZxnM7+jttG4QHiDAu6BXKPFnin0QGamTwtrT2jJkOhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-06T20:36:18Z"
    mac: ENC[AES256_GCM,data:pGMhKq2WfC0IXqie+oaoilNcDTI6gsmSB+ZGVyOkVYmKt8/dAsrhppDYkrprJCb38qM7lpvdNQrJ2Oqe1dx9glj/co2s8Mse1vuAtlYyEj1XLzdHRmsq535p/d3D2nrhN/cVEDYto1ERSDQnMVgMDyECtr2YNGtdxBmYwzUXhkA=,iv:hm8e1DtCLnV1++A8JGfn766M4QUJQTBR8SWEORmbuy4=,tag:Lxc6i0CaV3d5UbEOtrPB4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
