apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-settings
    namespace: flux-system
data:
    METALLB_LB_RANGE: ENC[AES256_GCM,data:eyrIYcvu6xkJr3EBaz1Hed1Bg7l6eJywmz8CH9o=,iv:SWsg1JzjwYfSgzvBOZ/QpO71QbwCCVKr/Kw9Eqphkio=,tag:dwV3LYYNbQy4+iaoKMCmew==,type:str]
    METALLB_TRAEFIK_ADDR: ENC[AES256_GCM,data:mjTVLEJhmYSCOGwAq3o=,iv:/hs2Wu1hs5Euu3P7i6udjTqT6XpYFMFISzzVs2+2gq4=,tag:PZpphUre+gTIVYTOy39CHg==,type:str]
    #ENC[AES256_GCM,data:0S07u0Gi/zLoA01oZ5r1PgNw,iv:MorpmwbFE2c/UHEQlh18b10YCbIq9cB1viwsAMsLNlM=,tag:wtkYbOaTBgnW79e1zAYFPg==,type:comment]
    LB_PLEX: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15mqr05vqgqh5h5rfa27ym6r8jgpdtpxy8j8wlnx5a42ptdan53kq6c0u4j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodDhyODVicFFUTy8zOGYw
            TzJ3MStDSjdSSWpSbWczQk9EQ1A0RG5Oc0FBCkhLT0dTUXdPcy9YQ29pdGIyZVlo
            UmRweUFsLyswUHBkNFMvQXNTcVlTWkEKLS0tIHZPaHlqbXlSaWNyRy9ZbVM5WmpS
            VjBodkVsM3VkWFJaSWZGUy80Witnc00KBmaVJOpi4NuRqTVHpxnvgm6vel63n/Yn
            KQ8zKIv19HJPyEVAFYly44wlZgmuS5Gr8zs4r/Zfqecsc2tyOfZQrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-06T08:51:57Z"
    mac: ENC[AES256_GCM,data:eDfHuYiZxQ8Y9YFlO6t/54GZhsefLDVphm2WZh/oE+C3AFbMa0zeVuO2E1dJMxyUcVx24Pnmh1FE6EEpQxfHhlBoK8tLhNZIW9N9fEgeSN3J0EcVFWoSGyuVWzvzUGuBALjgWPxngllwu0mAOYJY/y7k6H/6MH/R5OrjBniu9IM=,iv:aCN0vc4XxwKl4kncIlWUR7mmpLATCODEEBBaZ/YW6wI=,tag:QvBw4zgnka7XG/yx2XnqiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
