apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-settings
    namespace: flux-system
data:
    METALLB_LB_RANGE: ENC[AES256_GCM,data:5zfCHVWgqh/F21sZxiQLCauNpyOrNCkBixafV2s=,iv:KlICB/mrc+AqVeWiEdd6KdGQA8l+IsR5EaEzZW6yYXU=,tag:7PL5947/FUf52TQ6kQMvLg==,type:str]
    METALLB_TRAEFIK_ADDR: ENC[AES256_GCM,data:DJacL2JVvjYZGlnbREI=,iv:Z/tj3uclOOb39W3FK49AAPkwf9bBYS7Og5rNa+8iQE0=,tag:hunoWQdUkfVIRcTxfWzaPg==,type:str]
    #ENC[AES256_GCM,data:WdS0iZyGOpcCDLNhNsyTGa7E,iv:fHiKxUgHvC1oJxOevgvG+iUqby9OO5vGN2SJkvvujBU=,tag:aq2BPxIQnpGrVXDbZT8wQQ==,type:comment]
    LB_PLEX: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cppk2mmfs9aq58wveyktr4xjcg3vfju506qn282z3z0ml0eejd4qtvcda4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbFVjOFB6WE9Rcjd4SXNt
            MTFJc2Q4YWZwSlc0TnRYcS9XTytVVFIzeTFrCjA4dHUyTGFyZmQ0dnlWQTVHdTlE
            MEowYStmeXRVck1JUC9mVG5DVVRrNDgKLS0tIC9SQTFFemhLUnlucy81U1YwYWxE
            RHZnN0grcW16REYrVGtGWXZLZDhWZlkK/Ischrlqn9+KZ8O/Ok4MfyqPybjO5Pnz
            JNzdIAE8YzxUj7P1h8iA1JDdHbNMUtzgonKiuYjjPXtyQ1rS8wm2+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-06T08:09:50Z"
    mac: ENC[AES256_GCM,data:xVJPCSCrXHnyWDlVfH9adZnbx+ehdvAcAz+Mw5VUQccxYd+27pL9QKykASygmnby/c1fSftlZ7tyNA/jg+DQ7NKB/DpUB9YHDjq/NeRwEw7UIHbSEVXfw2dWLvkNHw+VLKSNY1RCMPf7F7Di8sMlhpzVdxQUm32q8RRO8I6M5YU=,iv:7SpRo8XpNa/H/nlG7YlrjdKdbXPhEkZgLJh8MBBOLVE=,tag:uKWR2ci5JK31SzfES8xqgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
