apiVersion: v1
kind: Secret
metadata:
    name: global-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:AsIcRp6aMnk=,iv:Hkm4EZ4X4ZPffvlno+LeOnTR8OQngFvc5rqGmeiHLDw=,tag:1sHsCWDalrTMK2fbjGGaMQ==,type:comment]
    FAMILY_DOMAIN: ENC[AES256_GCM,data:j/F1t6dp7g==,iv:JLSfob4Zqpxzb2EAJ+/HuIcMsRjxEaiN9SszkBdWg64=,tag:p4qg6qcQgmtzxY1dWp1zhA==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:WzYs+Ek=,iv:KC699kftEj1wbnUAzbUyTQxSBQB9n0Xqu8hQ97TGGC0=,tag:SKdrlctQEEAeClYrogKf4A==,type:str]
    INGRESS_DOMAIN: ENC[AES256_GCM,data:iNYWSK/gkom43Rr6RA==,iv:UcpKEnMZ6eAcBnOf7xRAilu18uds1ulwWpJuBNer5F4=,tag:8SrD2mLLRcHZtBiaKkVbjw==,type:str]
    PERSONAL_DOMAIN: ENC[AES256_GCM,data:DByS1B8=,iv:yM/0pfSk5Rt9l4IgUqfUGDajdrwRHh4QgtYXXBZPb/E=,tag:sqRK+I699InKWJ3to7HuHQ==,type:str]
    #ENC[AES256_GCM,data:CJvZ4Dhn4Q==,iv:GPGSGePpogMCuttMWox1y0Ks2baOCFOmGBMRHMpQgDw=,tag:ts/K5WqDsBhpJj57imySGw==,type:comment]
    EMAIL_1: ENC[AES256_GCM,data:DkfKLlsOHXwqxW8Ud5A=,iv:DZvG/ejof3SBEToLa9Z+3YCsS9OjAxMH51OvAhdQLBo=,tag:WH03w4e7UsWjfhdaBPTcUw==,type:str]
    EMAIL_2: ENC[AES256_GCM,data:aNdYTzuMhpimQi2TdijOuq8VOA8=,iv:juyATz1RefXU7GqB4tuOlIqgkm7Rr6VQL2wiK8jdfDQ=,tag:Fz26HheEtsqkcwS8fqMKsg==,type:str]
    EMAIL_POSTMASTER: ENC[AES256_GCM,data:vRNQFTp4hHIzL40unymu0kYCFlaqVA==,iv:BPeBLnsqgSMFRU4A/0ijf2agoQ3rOJeMo/Q20b/z7fI=,tag:LoKU69LgYh5D5XnBfconMw==,type:str]
    #ENC[AES256_GCM,data:s/+BR3rlDbW8d4elO/XJoaWiiw==,iv:UQ9Lrw+BWXoL9v9eb21KkK6sGe5UAPwxYfsQD57fyMU=,tag:26IPpTakS4Mvy0TEKyLbvQ==,type:comment]
    NAS_ADDRESS: ENC[AES256_GCM,data:+/Hnyk63FxzlcEyOpw==,iv:l99fCcNLRv1TS04hVq45nENPVExQFB7kwn0or8rryk4=,tag:l9WMgN2O9bGBov+efqDgpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ekhztvazxdqa67xyu2v0fy9cn6y8t6awta2wnrz66agv2dmq7g0qfkg7lp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a0c3Q1dXNWR1R1UraEo1
            WFVVbEx4RnVtNFRYdUZtOFBhM1dWSjBDNnhrCllMMVhxUTNpVTFLYjJKMkRtQ2ZG
            TmNwV0xYOUFseGdrRitjM28rRERNUlEKLS0tIElNcmNtOFlldnVQSWVTMnFDejNq
            bURyVU5YVEV1S1prYzV2eE1vNEpleVkKCQ3XEAbTuhuMcIglAi2gPtO+MCy8K5G2
            n7upZRcmAiHpRzdg3Ry6dgs0VvBPyV5PVWFoZf5NIt1XztMLS07CiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T11:38:02Z"
    mac: ENC[AES256_GCM,data:jR1Au0mOcHk71i9ty8oNlinoaYMKe2lq3dzcUW/WmuR/G4AGAyG3vsSaRlft4IdpxOTMKvuMCwainj+0ZSwkyxBBmd6zmvkT0vLjpb//dXR/sBV8GZecHyL0xujdKQ9uP06IQEJdQWZOrDNdcXkizJexIFMxiu0lUT9zMRLzBvg=,iv:2ozSRXvwWdfMs8QwfSqRcZb2lERrYqxsZreKfJipr3k=,tag:c5mXgpp11N48DJV5mdGVKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
