apiVersion: v1
kind: Secret
metadata:
    name: global-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:/SWamxZsC4I=,iv:c/KxwmKxn+el6kZ1PaNvH9sMwsAuvV8buvfACou8afc=,tag:W8VXUIVyK2PJcZDEa6trzw==,type:comment]
    FAMILY_DOMAIN: null
    HARDWARE_DOMAIN: null
    INGRESS_DOMAIN: null
    PERSONAL_DOMAIN: null
    #ENC[AES256_GCM,data:k+htcfmLPg==,iv:yIL/0HG0MOmXWrbnH5XBN4J2S9vtuY0pVLw3uDi3Zh8=,tag:Gat8VdvofkfQyOg8qFztPw==,type:comment]
    EMAIL_1: null
    EMAIL_2: null
    EMAIL_POSTMASTER: null
    #ENC[AES256_GCM,data:Kj1WdeuP5rD3VHz30E4T/B7FxQ==,iv:LY9cvAP/qutocOZPFDxjexhQvrfppol6S3MZckdUIH0=,tag:j92HPEKftP3qzvudnQY+BQ==,type:comment]
    NAS_ADDRESS: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15mqr05vqgqh5h5rfa27ym6r8jgpdtpxy8j8wlnx5a42ptdan53kq6c0u4j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzb21DYXVxek44RlBKYVIy
            N3psOUVwT2hVU1FKRzkxS2s4dkh6dWNQZnpFCmpDUWFGRVhtWTVTKzl2MkFWM0pr
            S3dIRUNhaHgxcEc5QTBNMEpwdHpXWEEKLS0tIDY5M0FiMlR3Q2RPN3pSYTg1VVJ1
            WDM0V2JjZ1FmdjFLekIyR0dsVzJnRU0Kn6s0UM5sijlWknVHx62Fm5NrYnLMYqCX
            6XA/jwmaSHfudCYGtppVaB40z8ETqRnuHEagZo/hopHHij0Vo3MHhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-06T08:51:56Z"
    mac: ENC[AES256_GCM,data:vbqIJ1g+0Vom/YBa7S+kFcCiwYoao158KBXVrEO4S44PaEwW8Up+GD8h58KBMiApf+d0jLtkwHo92WIbjN5k1QhVVJOLN3/Ad5p4YfQdxOKPdjt/15I0sKpE3GedklHO3/36f8/hXsTK2BPYnz1PdaxGqpdhCTYlUD4qYxOBBeE=,iv:TUskdkpLvseAR9d7zpObxWmT6WUiDXNHxIXMRG/KwlY=,tag:fq8VZ8eKynrbmPV7aBX0Cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
