# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:A+/AhcmT8B8hukNIgjRQEaCVtDVOLgpUh+Wq7uSXAPanjR9lUQ==,iv:HHOk0WjcmifBw89nLivoojdatX6RHgLwiPWuAteHxgU=,tag:gj5SoBKaRt/LE4YY/Yq1vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15mqr05vqgqh5h5rfa27ym6r8jgpdtpxy8j8wlnx5a42ptdan53kq6c0u4j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2azV3S1lrVGhTVXhxMU00
            SWZDUGZRRlJaSzNBKzlVOWJBRHNSamdQcWdJCjBJck5kdEllVGtIK2EzMUthMDB4
            dUpYM0thd3huTFl4SzFxV0NWazljcmcKLS0tIGgzTnZSUWZFRUdtcy96SzAvdjZH
            cUg0YVQ3ejdCdCszZ1FpTFdnZ1Z0clEKrcFXf1aA0gCyPsc1hZOA1/flPpxDWEgm
            3zuHnfY7l8GPNElFDeoCwnO5qjJk3oDDN/MImhjd8QifVu0YvYbWwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-06T08:51:57Z"
    mac: ENC[AES256_GCM,data:i4dT6ihEEC8GNWDc0/2DnrdZegCQfMyBEYL072CmZNxvk1Zf8hjYpKgiPGJnlrOEZ5oRYGIdpoWLk3537QHoiSmvk/7PPTd9XwZeSCkkWMF41RjaK4Q/5j0oE4u1T7cZJ6Vv4zQ8AX31W917tD42rZJkQvBhuDDJcG6ddf6armc=,iv:y6tXSn+mE/wTMLmr+2NJSbmaddibcQ9qqKlH/MXcykE=,tag:KqpKsGjxLjRif1YvQYYcfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
