# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:8Gtn83rFOh7KQE0ysjZL5S0cT90OMKWU/hwyn+9OiB4MMp/6IQ==,iv:Kzyh0hd51uawwkJzaOs2xC2pi3a9uEH6Sou7dkYZNEQ=,tag:Y2LXwnpMjU9GZwOws/CEhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c6mdht8t32akamkzrlll7ntvcueezvx976kerzga96hy4agkqcgqe3y9kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZnZKaHV0bTNTRVFEWVRK
            Mjk0TG1zMjFDdDdTMmVDQk9CSGUzYnhiRlVBClREWTlUcDRpZWFBMGUrcDlDVGZV
            VEV1aitoUHRSbnRxY1Y2cmtGMEFLS2MKLS0tIGFFVkJpVmxnSGx4a2x4U3FNVGFt
            N1pKcEZmODBUbVhGc1FNNHNxZ0FCU0UKalIwGIlq3VxYwnl1K9d+ERLVLvgsmrdW
            jjefII0FmKQBOIFCcMj48LefZ8hAIVkMdY+5KbAgd04nbf2qXHDF1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-02T23:36:54Z"
    mac: ENC[AES256_GCM,data:S376t0EVB6IY3kjepCrUgamjML5Uo+v/ar3BZNl20v2dFJdA5F7srUoknKZJuF7Aa+/kKtvWpBwPyPBeCIMWjIbZdJn2YNWbziRT3JecwncJKIRL4oiaaN/e97FosOo6kONtOTxgsttcvtoe5ZE7qnCF0PZ5CjHIn30OxzfYQ6I=,iv:x9Y5puFHNLWPx2PVCnsWxavLDN9GmqT7WRccbdWyCFk=,tag:iriLx06Zf98VMQ65YbtqwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
