---
name: 'Template Sync'

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: narrowspark/template-sync-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          template_repository: k8s-at-home/template-cluster-k3s
          ref: refs/heads/master